### ISSUE TITLE
The relationship between disparity map and confidence map.

### ISSUE THREAD

**Issue by TrackingBird** [fabiotosi92/CCNN-Tensorflow#2]
Dear sir, thanks for your wonderful work. I test your algorithm with middlebury 2014dataset. Whether lighter color indicate higher confidence in confidence map? Whether warmer color and closer point in disparity map means lower confidence and dark color in confidence map?
Thanks for your help.

**Comment by fabiotosi92** [comment]
Hi, 

Disparity map: warm colors encode closer points, cold for farther ones (using JET colormap for example). Instead, if you use a grayscale representation for disparity, higher values stand for closer points. 
Confidence map: brighter values for high confidence, darker for low confidence.

"Warmer color and closer point in disparity map means lower confidence and dark color in confidence map": No, confidence estimation depends only on recurrent patterns that characterize wrong and correct disparity assignments. If you have high disparity values the confidence estimation could be high as well.
