### ISSUE TITLE
A question about training datasets

### ISSUE THREAD

**Issue by Rythsman** [fabiotosi92/CCNN-Tensorflow#3]
Hi, Do you use flythings3D as dataset to evaluate your confidence measures CCNN? When I use disparity map from dispnet/mc-cnn with flythings3D, my output seems not right, the front scenes are black. Can you give me some suggestions or could you tell me where to change the code? Thx.

**Comment by mattpoggi** [comment]
Hi @Rythsman ,
we ran a few experiments on the outputs of DispNet processing FlyingThings3D images and it worked. 
Of course, you need to train your own CCNN on FlyingThings as well. The weights we provide come from KITTI dataset on which the maximum disparity observable is about 200,  while you may easily find disparities up to 300 on FlyingThings.

**Comment by Rythsman** [comment]
@mattpoggi , thanks for your response.
